#!/bin/zsh

umask 0002

typeset -U path
path=(~/bin ~/local/bin /usr/local/bin /usr/local/sbin $path)

export EDITOR=vim

if [ $(uname) = 'Darwin' ]; then
  export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home
fi

if [ -n DISPLAY ]; then
  export DISPLAY=:0.0
fi

__which() {
    /usr/bin/which $1 >/dev/null
}

[[ -s "/Users/joellongtine/.rvm/scripts/rvm" ]] && source "/Users/joellongtine/.rvm/scripts/rvm"

export NODE_PATH="/usr/local/lib/node_modules:$NODE_PATH"
